<?php

/**
 * @file
 * Handles the installation for LESS
 * 
 * 
 */

function less_install() {
  $locale_weight = db_select('system', 's')
    ->fields('s', array('weight'))
    ->condition('name', 'locale', '=')
    ->execute()
    ->fetchField();
    
  db_update('system')
    ->fields(array(
      'weight' => ++$locale_weight,
    ))
    ->condition('name', 'less', '=')
    ->execute();
}

function less_update_7200() {
  less_install();
}
