<?php

/**
 * Implements hook_menu().
 */
function less_demo_menu() {
  $items = array();

  $items['admin/config/development/less/demo'] = array(
    'title' => 'LESS Demo',
    'description' => 'Demonstration for less features',
    'page callback' => '_less_demo_page',
    'access arguments' => array(LESS_PERMISSION),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function less_demo_admin_paths() {
  return array(
    'admin/config/development/less/demo' => FALSE,
  );
}

/**
 * Implements hook_less_variables().
 * 
 * Should return flat associative array, where key is variable name.
 * Variables returned by this function are cached.
 * 
 * @see less_demo_less_variables_alter().
 */
function less_demo_less_variables() {
  return array(
    '@test' => '#ccc',
  );
}

/**
 * Implements hook_less_variables_alter().
 * 
 * @param $less_variables
 *   Flat associative array of variables, where key is variable name.
 * @param $context
 *   Array containing one value, the system_name of the module or theme that
 *   this applies to: array('system_name' => $system_name);
 */
function less_demo_less_variables_alter(&$less_variables, $context) {
  dpm(func_get_args());
}

/**
 * Implements hook_less_functions().
 */
function less_demo_less_functions() {
  return;
  return array(
    'url' => function ($args) {
      return 'blarg';
    },
  );
}

/**
 * Implements hook_less_functions_alter().
 * 
 * @param $less_functions
 *   Flat associative array of functions, where key is variable and value is
 *   function name or Anonymous function: 
 *   (http://php.net/manual/en/functions.anonymous.php)
 * @param $context
 *   Array containing one value, the system_name of the module or theme that
 *   this applies to: array('system_name' => $system_name);
 */
function less_demo_less_functions_alter($less_functions, $context) {
  // dpm(func_get_args());
}

function urlreplacement($args, $less) {
  return 'blarg';
}

function _less_demo_page() {
  global $theme;
  
  $output = '';
  
  $file_less_settings = array(
    'variables' => array(
      '@gradient_end' => '#bada55',
    ),
  );
  
  drupal_add_css(drupal_get_path('module', 'less_demo') . '/styles/less_demo.drupal_add_css.css.less', array('less' => $file_less_settings));
  
  $output .= '<div class="less_demo_logo"></div>';
  
  $output .= '<p>' . l('Configure current theme', 'admin/appearance/settings/' . $theme) . '</p>';
  
  // wrap
  $output = '<div id="less_demo_gradient">' . $output . '</div>';
  
  return $output;
}
